// Inserciones para la coleccion de albums

db.albums.insertMany([{
    "sku":"M101",
    "title":"Back in Black",
    "artist":"AC/DC",
    "genre":"Rock",
    "release_year":1980,
    "format":"Vinilo",
    "price":95000,
    "stock":8,
    "raiting":4.9,
    "tags":["clásico","coleccionable","edición especial"],
    "label":{"name":"Atlantic Records","country":"Estados Unidos"}
    },
    {"sku":"M034",
    "title":"El Madrileño",
    "artist":"C. Tangana",
    "genre":"R&B",
    "release_year":2018,
    "format":"Vinilo",
    "price":70000,
    "stock":15,
    "raiting":4.6,
    "tags":["español","flamenco"],
    "label":{"name":"World Records","country":"España"}
    },
    {"sku":"M018",
    "title":"No te vayas",
    "artist":"Camilo",
    "genre":"Reguetón",
    "release_year":2018,
    "format":"Vinilo",
    "price":30000,
    "stock":25,
    "raiting":4.2,
    "tags":["colombia","edición especial"],
    "label":{"name":"Tiny Records","country":"Estados Unidos"}
    },
    {"sku":"M059",
    "title":"Heterosexuales por Opcion",
    "artist":"Blondon Boys",
    "genre":"Alternativo",
    "release_year":2014,
    "format":"Disco",
    "price":5000,
    "stock":43,
    "raiting":3.2,
    "tags":["experimental","indie"],
    "label":{"name":"Youfilm Records","country":"Chile"}
    },
    {"sku":"M012",
    "title":"Por Cesarea",
    "artist":"Dillom",
    "genre":"Indie",
    "release_year":2024,
    "format":"Disco",
    "price":10000,
    "stock":15,
    "raiting":4.8,
    "tags":[],
    "label":{"name":"Music Center","country":"Argentina"}
    },
    {"sku":"M025",
    "title":"Dance Dance",
    "artist":"Fall Out Boys",
    "genre":"Pop-punk",
    "release_year":2016,
    "format":"Vinilo",
    "price":15000,
    "stock":20,
    "raiting":4.7,
    "tags":["pop-rock"],
    "label":{"name":"Music VO","country":"Estados Unidos"}
    },
    {"sku":"M099",
    "title":"Thriller",
    "artist":"Michael Jackson",
    "genre":"Pop",
    "release_year":1985,
    "format":"Vinilo",
    "price":40000,
    "stock":5,
    "raiting":4.9,
    "tags":["clásico","edición especial","coleccionable"],
    "label":{"name":"US Records","country":"Estados Unidos"}
    },
    {"sku":"M098",
    "title":"I Want You Back",
    "artist":"Jackson 5",
    "genre":"Pop",
    "release_year":1960,
    "format":"Vinilo",
    "price":38000,
    "stock":18,
    "raiting":4.6,
    "tags":["clásico"],
    "label":{"name":"Vintage Records","country":"Estados Unidos"}
    },
    {"sku":"M001",
    "title":"Come And Get Your Love",
    "artist":"Redbone",
    "genre":"Country",
    "release_year":1970,
    "format":"Vinilo",
    "price":23000,
    "stock":3,
    "raiting":4.5,
    "tags":["clásico","marvel"],
    "label":{"name":"Vintage Records","country":"Estados Unidos"}
    },
    {"sku":"M934",
    "title":"La Casa Verde",
    "artist":"Rupatrupa",
    "genre":"Acustico",
    "release_year":2020,
    "format":"Disco",
    "price":15000,
    "stock":0,
    "raiting":3.7,
    "tags":["colombia","edición especial"],
    "label":{"name":"Tiny Records","country":"Colombia"}
    },
    {"sku":"M134",
    "title":"The One That Got Away",
    "artist":"Katy Perry",
    "genre":"Pop",
    "release_year":2012,
    "format":"Vinilo",
    "price":54000,
    "stock":2,
    "raiting":4.6,
    "tags":["edición especial"],
    "label":{"name":"Music Factory","country":"Estados Unidos"}
    },
    {"sku":"M338",
    "title":"You Bellong With Me",
    "artist":"Taylor Swift",
    "genre":"Country",
    "release_year":2014,
    "format":"Disco",
    "price":24000,
    "stock":23,
    "raiting":4.1,
    "tags":[],
    "label":{"name":"Desk Records","country":"Estados Unidos"}
    },
    {"sku":"M043",
    "title":"I Love It Loud",
    "artist":"KISS",
    "genre":"Rock",
    "release_year":1985,
    "format":"Vinilo",
    "price":80000,
    "stock":3,
    "raiting":4.9,
    "tags":["clásico"],
    "label":{"name":"Atlantic Records","country":"Estados Unidos"}
    },
    {"sku":"M256",
    "title":"Nuestro Amor Será",
    "artist":"Bohemia",
    "genre":"Merengue",
    "release_year":1995,
    "format":"Vinilo",
    "price":45000,
    "stock":0,
    "raiting":4.9,
    "tags":["colombia","edición especial"],
    "label":{"name":"Tiny Records","country":"Colombia"}
    },
    {"sku":"M456",
        "title":"Obsceno",
        "artist":"Kaze",
        "genre":"Jazz",
        "release_year":2019,
        "format":"Disco",
        "price":16000,
        "stock":5,
        "raiting":3.9,
        "tags":["adultos"],
        "label":{"name":"Spain Records","country":"España"}
        }
    ])